export const ITEM_LIMIT = 5;
export const DATE_FORMAT = { weekday: "long", year: "numeric", month: "long", day: "numeric" };
export const LONG_DATE_FORMAT = { dateStyle: "full", timeStyle: "medium" };
export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";
export const HIDE_SIDEBAR = "HIDE_SIDEBAR";
export const SHOW_SIDEBAR = "SHOW_SIDEBAR";
export const SET_LOGIN_ERROR = "SET_LOGIN_ERROR";
export const CLEAR_LOGIN_ERROR = "CLEAR_LOGIN_ERROR";
export const SET_CURRENT_COMPANY = "SET_CURRENT_COMPANY";
export const SET_CURRENT_PROJECT = "SET_CURRENT_PROJECT";
export const compareTime = (a, b) => new Date(b.timeCreated) - new Date(a.timeCreated);
